### ISSUE TITLE
Raise constAddressDeployer gasLimit multiplier

### ISSUE THREAD

**Issue by 0x1NotMe** [axelarnetwork/axelar-gmp-sdk-solidity#18]
I was trying to deploy a contract using the constAddressDeployer (deployContractConstant)
But I was getting some error which wasn't particular useful upon further investigation
I realised that Arbitrum gas usage works different than other EVM and L1 calldata adds overhead
so that the current multiplier was insufficient. 

```js
const tx = await deployer
    .connect(wallet)
    .deploy(bytecode, salt, { gasLimit: BigInt(Math.floor(gas * 1.2)) });
```
I could deploy by increasing the multiplier to 2

**Comment by re1ro** [comment]
Thank you @0x1NotMe ! Will be fixed in this PR #19
